### ISSUE TITLE
round function in tools.py

### ISSUE THREAD

**Issue by frba** [Edinburgh-Genome-Foundry/Plateo#2]
I was testing the function: compute_rows_columns and when I used it for a plate with 48 wells, it returns num_roqs = 6, num_cols = 9 instead of 6, 8.
If you change the round and int cast to after the multiplication it'll work.

def compute_rows_columns(num_wells):
    """Convert 96->(8,12), 384->(16,24), etc."""
    a = int(np.round(np.sqrt(num_wells / 6)))
    n_rows = 2*a
    n_columns = 3*a
    return n_rows, n_columns

def compute_rows_columns(num_wells):
    """Convert 96->(8,12), 384->(16,24), etc."""
    a = np.sqrt(num_wells / 6)
    n_rows = int(np.round(2*a))
    n_columns = int(np.round(3*a))
    return n_rows, n_columns

**Comment by Zulko** [comment]
Indeed. Thanks for the report and the fix! Plateo is now fixed on Github and on Pypi. Let us know if you run into any other trouble with the library.
